v1=str(input("introduce tu nombre: "))
v2=str(input("introduce tu carrera: "))
v3=str(input("introduce tu semestre: "))
v4=str(input("introduce tu materia: "))
print("tu nombre es: ",v1,", tu carrera es: ",v2,", tu semestre es: ",v3," y tu materia es:",v4)